package th.go.rd.rdepaymentservice.entity;
// Generated Aug 6, 2018 3:54:47 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * EpayTaxPaymentInboundRefOutbound generated by hbm2java
 */
@Entity
@Table(name = "EPAY_TAX_PAYMENT_INBOUND_REF_OUTBOUND")
public class EpayTaxPaymentInboundRefOutbound implements java.io.Serializable {

	private long epayTaxPaymentInboundRefOutboundId;
	private EpayTaxPaymentInbound epayTaxPaymentInbound;
	private EpayTaxPaymentOutbound epayTaxPaymentOutbound;

	public EpayTaxPaymentInboundRefOutbound() {
	}

	public EpayTaxPaymentInboundRefOutbound(long epayTaxPaymentInboundRefOutboundId, EpayTaxPaymentInbound epayTaxPaymentInbound, EpayTaxPaymentOutbound epayTaxPaymentOutbound) {
		this.epayTaxPaymentInboundRefOutboundId = epayTaxPaymentInboundRefOutboundId;
		this.epayTaxPaymentInbound = epayTaxPaymentInbound;
		this.epayTaxPaymentOutbound = epayTaxPaymentOutbound;
	}

	@Id
	@SequenceGenerator(name="EPAY_TAX_PAYMENT_INBOUND_REF_OUTBOUND_ID_SEQ", sequenceName="EPAY_TAX_PAYMENT_INBOUND_REF_OUTBOUND_ID_SEQ", allocationSize=1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="EPAY_TAX_PAYMENT_INBOUND_REF_OUTBOUND_ID_SEQ")
	@Column(name = "EPAY_TAX_PAYMENT_INBOUND_REF_OUTBOUND_ID", unique = true, nullable = false)
	public long getEpayTaxPaymentInboundRefOutboundId() {
		return this.epayTaxPaymentInboundRefOutboundId;
	}

	public void setEpayTaxPaymentInboundRefOutboundId(long epayTaxPaymentInboundRefOutboundId) {
		this.epayTaxPaymentInboundRefOutboundId = epayTaxPaymentInboundRefOutboundId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EPAY_TAX_PAYMENT_INBOUND_ID", nullable = false)
	public EpayTaxPaymentInbound getEpayTaxPaymentInbound() {
		return this.epayTaxPaymentInbound;
	}

	public void setEpayTaxPaymentInbound(EpayTaxPaymentInbound epayTaxPaymentInbound) {
		this.epayTaxPaymentInbound = epayTaxPaymentInbound;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EPAY_TAX_PAYMENT_OUTBOUND_ID", nullable = false)
	public EpayTaxPaymentOutbound getEpayTaxPaymentOutbound() {
		return this.epayTaxPaymentOutbound;
	}

	public void setEpayTaxPaymentOutbound(EpayTaxPaymentOutbound epayTaxPaymentOutbound) {
		this.epayTaxPaymentOutbound = epayTaxPaymentOutbound;
	}

}
