package th.go.rd.rdepaymentservice.entity;
// Generated Nov 21, 2018 11:27:54 AM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EpayTaxPaymentInfoDetail generated by hbm2java
 */
@Entity
@Table(name = "EPAY_TAX_PAYMENT_INFO_DETAIL")
public class EpayTaxPaymentInfoDetail implements java.io.Serializable {

	private long epayTaxPaymentInfoDetailId;
	private EpayTaxPaymentInfo epayTaxPaymentInfo;
	private String sysRefNo;
	private String formCode;
	private BigDecimal totalAmount;
	private String nid;
	private String paymentMessage;
	private String createBy;
	private Date createDate;
	private String updateBy;
	private Date updateDate;
	private String nidBraNo;
	private BigDecimal netTaxAmount;
	private BigDecimal penaltyAmount;
	private BigDecimal totalTaxAmount;
	private BigDecimal criminalFinesAmount;
	private BigDecimal taxAmount;
	private BigDecimal surchargeAmount;
	private Character isRound;

	public EpayTaxPaymentInfoDetail() {
	}

	public EpayTaxPaymentInfoDetail(long epayTaxPaymentInfoDetailId, EpayTaxPaymentInfo epayTaxPaymentInfo, String sysRefNo, String formCode, BigDecimal totalAmount, String nid, String createBy,
			Date createDate, String updateBy, Date updateDate, String nidBraNo) {
		this.epayTaxPaymentInfoDetailId = epayTaxPaymentInfoDetailId;
		this.epayTaxPaymentInfo = epayTaxPaymentInfo;
		this.sysRefNo = sysRefNo;
		this.formCode = formCode;
		this.totalAmount = totalAmount;
		this.nid = nid;
		this.createBy = createBy;
		this.createDate = createDate;
		this.updateBy = updateBy;
		this.updateDate = updateDate;
		this.nidBraNo = nidBraNo;
	}
	public EpayTaxPaymentInfoDetail(long epayTaxPaymentInfoDetailId, EpayTaxPaymentInfo epayTaxPaymentInfo, String sysRefNo, String formCode, BigDecimal totalAmount, String nid, String paymentMessage,
			String createBy, Date createDate, String updateBy, Date updateDate, String nidBraNo, BigDecimal netTaxAmount, BigDecimal penaltyAmount, BigDecimal totalTaxAmount,
			BigDecimal criminalFinesAmount, BigDecimal taxAmount, BigDecimal surchargeAmount, Character isRound) {
		this.epayTaxPaymentInfoDetailId = epayTaxPaymentInfoDetailId;
		this.epayTaxPaymentInfo = epayTaxPaymentInfo;
		this.sysRefNo = sysRefNo;
		this.formCode = formCode;
		this.totalAmount = totalAmount;
		this.nid = nid;
		this.paymentMessage = paymentMessage;
		this.createBy = createBy;
		this.createDate = createDate;
		this.updateBy = updateBy;
		this.updateDate = updateDate;
		this.nidBraNo = nidBraNo;
		this.netTaxAmount = netTaxAmount;
		this.penaltyAmount = penaltyAmount;
		this.totalTaxAmount = totalTaxAmount;
		this.criminalFinesAmount = criminalFinesAmount;
		this.taxAmount = taxAmount;
		this.surchargeAmount = surchargeAmount;
		this.isRound = isRound;
	}

	@Id
	@SequenceGenerator(name="EPAY_TAX_PAYMENT_INFO_DETAIL_ID_SEQ", sequenceName="EPAY_TAX_PAYMENT_INFO_DETAIL_ID_SEQ", allocationSize=1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="EPAY_TAX_PAYMENT_INFO_DETAIL_ID_SEQ")
	@Column(name = "EPAY_TAX_PAYMENT_INFO_DETAIL_ID", unique = true, nullable = false)
	public long getEpayTaxPaymentInfoDetailId() {
		return this.epayTaxPaymentInfoDetailId;
	}

	public void setEpayTaxPaymentInfoDetailId(long epayTaxPaymentInfoDetailId) {
		this.epayTaxPaymentInfoDetailId = epayTaxPaymentInfoDetailId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EPAY_TAX_PAYMENT_INFO_ID", nullable = false)
	public EpayTaxPaymentInfo getEpayTaxPaymentInfo() {
		return this.epayTaxPaymentInfo;
	}

	public void setEpayTaxPaymentInfo(EpayTaxPaymentInfo epayTaxPaymentInfo) {
		this.epayTaxPaymentInfo = epayTaxPaymentInfo;
	}

	@Column(name = "SYS_REF_NO", nullable = false, length = 20)
	public String getSysRefNo() {
		return this.sysRefNo;
	}

	public void setSysRefNo(String sysRefNo) {
		this.sysRefNo = sysRefNo;
	}

	@Column(name = "FORM_CODE", nullable = false, length = 20)
	public String getFormCode() {
		return this.formCode;
	}

	public void setFormCode(String formCode) {
		this.formCode = formCode;
	}

	@Column(name = "TOTAL_AMOUNT", nullable = false, precision = 16)
	public BigDecimal getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(BigDecimal totalAmount) {
		this.totalAmount = totalAmount;
	}

	@Column(name = "NID", nullable = false, length = 20)
	public String getNid() {
		return this.nid;
	}

	public void setNid(String nid) {
		this.nid = nid;
	}

	@Column(name = "PAYMENT_MESSAGE", length = 200)
	public String getPaymentMessage() {
		return this.paymentMessage;
	}

	public void setPaymentMessage(String paymentMessage) {
		this.paymentMessage = paymentMessage;
	}

	@Column(name = "CREATE_BY", nullable = false, length = 20)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", nullable = false, length = 26)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "UPDATE_BY", nullable = false, length = 20)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DATE", nullable = false, length = 26)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "NID_BRA_NO", nullable = false, length = 6)
	public String getNidBraNo() {
		return this.nidBraNo;
	}

	public void setNidBraNo(String nidBraNo) {
		this.nidBraNo = nidBraNo;
	}

	@Column(name = "NET_TAX_AMOUNT", precision = 18)
	public BigDecimal getNetTaxAmount() {
		return this.netTaxAmount;
	}

	public void setNetTaxAmount(BigDecimal netTaxAmount) {
		this.netTaxAmount = netTaxAmount;
	}

	@Column(name = "PENALTY_AMOUNT", precision = 18)
	public BigDecimal getPenaltyAmount() {
		return this.penaltyAmount;
	}

	public void setPenaltyAmount(BigDecimal penaltyAmount) {
		this.penaltyAmount = penaltyAmount;
	}

	@Column(name = "TOTAL_TAX_AMOUNT", precision = 18)
	public BigDecimal getTotalTaxAmount() {
		return this.totalTaxAmount;
	}

	public void setTotalTaxAmount(BigDecimal totalTaxAmount) {
		this.totalTaxAmount = totalTaxAmount;
	}

	@Column(name = "CRIMINAL_FINES_AMOUNT", precision = 18)
	public BigDecimal getCriminalFinesAmount() {
		return this.criminalFinesAmount;
	}

	public void setCriminalFinesAmount(BigDecimal criminalFinesAmount) {
		this.criminalFinesAmount = criminalFinesAmount;
	}

	@Column(name = "TAX_AMOUNT", precision = 18)
	public BigDecimal getTaxAmount() {
		return this.taxAmount;
	}

	public void setTaxAmount(BigDecimal taxAmount) {
		this.taxAmount = taxAmount;
	}

	@Column(name = "SURCHARGE_AMOUNT", precision = 18)
	public BigDecimal getSurchargeAmount() {
		return this.surchargeAmount;
	}

	public void setSurchargeAmount(BigDecimal surchargeAmount) {
		this.surchargeAmount = surchargeAmount;
	}

	@Column(name = "IS_ROUND", length = 1)
	public Character getIsRound() {
		return this.isRound;
	}

	public void setIsRound(Character isRound) {
		this.isRound = isRound;
	}

}
