package th.go.rd.rdepaymentservice.entity;
// Generated Jul 17, 2018 10:14:52 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * EpayKbankToken generated by hbm2java
 */
@Entity
@Table(name = "EPAY_KBANK_TOKEN")
public class EpayKbankToken implements java.io.Serializable {

	private long epayKbankTokenId;
	private EpayTaxPaymentInfo epayTaxPaymentInfo;
	private String tokenId;
	private String createBy;
	private Date createDate;
	private String updateBy;
	private Date updateDate;

	public EpayKbankToken() {
	}

	public EpayKbankToken(long epayKbankTokenId, EpayTaxPaymentInfo epayTaxPaymentInfo, String tokenId, String createBy, Date createDate, String updateBy, Date updateDate) {
		this.epayKbankTokenId = epayKbankTokenId;
		this.epayTaxPaymentInfo = epayTaxPaymentInfo;
		this.tokenId = tokenId;
		this.createBy = createBy;
		this.createDate = createDate;
		this.updateBy = updateBy;
		this.updateDate = updateDate;
	}

	@Id
	@SequenceGenerator(name="EPAY_KBANK_TOKEN_ID_SEQ", sequenceName="EPAY_KBANK_TOKEN_ID_SEQ", allocationSize=1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="EPAY_KBANK_TOKEN_ID_SEQ")
	@Column(name = "EPAY_KBANK_TOKEN_ID", unique = true, nullable = false)
	public long getEpayKbankTokenId() {
		return this.epayKbankTokenId;
	}

	public void setEpayKbankTokenId(long epayKbankTokenId) {
		this.epayKbankTokenId = epayKbankTokenId;
	}

	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EPAY_TAX_PAYMENT_INFO_ID", nullable = false)
	public EpayTaxPaymentInfo getEpayTaxPaymentInfo() {
		return this.epayTaxPaymentInfo;
	}

	public void setEpayTaxPaymentInfo(EpayTaxPaymentInfo epayTaxPaymentInfo) {
		this.epayTaxPaymentInfo = epayTaxPaymentInfo;
	}

	@Column(name = "TOKEN_ID", nullable = false, length = 20)
	public String getTokenId() {
		return this.tokenId;
	}

	public void setTokenId(String tokenId) {
		this.tokenId = tokenId;
	}

	@Column(name = "CREATE_BY", nullable = false, length = 20)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", nullable = false, length = 26)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "UPDATE_BY", nullable = false, length = 20)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DATE", nullable = false, length = 26)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
