package th.go.rd.rdepaymentservice.entity;
// Generated Jul 17, 2018 10:14:52 AM by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * EpayTaxPaymentOutbound generated by hbm2java
 */
@Entity
@Table(name = "EPAY_TAX_PAYMENT_OUTBOUND")
public class EpayTaxPaymentOutbound implements java.io.Serializable {

	private long epayTaxPaymentOutboundId;
	private EpayReceiverPaymentLine epayReceiverPaymentLine;
	private EpayTaxPaymentInfo epayTaxPaymentInfo;
	private MasterStatus masterStatus;
	private String uuid;
	private String tranNo;
	private String ctlCode;
	private Date transmitDate;
	private String attachFile;
	private String terminalId;
	private String merchantId;
	private String createBy;
	private Date createDate;
	private String updateBy;
	private Date updateDate;
	private String responseCode;
	private String responseMessage;
	private List<EpayTaxPaymentInboundRefOutbound> epayTaxPaymentInboundRefOutbounds = new ArrayList<>();

	public EpayTaxPaymentOutbound() {
	}

	public EpayTaxPaymentOutbound(long epayTaxPaymentOutboundId, EpayTaxPaymentInfo epayTaxPaymentInfo, MasterStatus masterStatus, String uuid, String createBy, Date createDate, String updateBy,
			Date updateDate) {
		this.epayTaxPaymentOutboundId = epayTaxPaymentOutboundId;
		this.epayTaxPaymentInfo = epayTaxPaymentInfo;
		this.masterStatus = masterStatus;
		this.uuid = uuid;
		this.createBy = createBy;
		this.createDate = createDate;
		this.updateBy = updateBy;
		this.updateDate = updateDate;
	}
	public EpayTaxPaymentOutbound(long epayTaxPaymentOutboundId, EpayReceiverPaymentLine epayReceiverPaymentLine, EpayTaxPaymentInfo epayTaxPaymentInfo, MasterStatus masterStatus, String uuid,
			String tranNo, String ctlCode, Date transmitDate, String attachFile, String terminalId, String merchantId, String createBy, Date createDate, String updateBy, Date updateDate,
			String responseCode, String responseMessage,List<EpayTaxPaymentInboundRefOutbound> epayTaxPaymentInboundRefOutbounds) {
		this.epayTaxPaymentOutboundId = epayTaxPaymentOutboundId;
		this.epayReceiverPaymentLine = epayReceiverPaymentLine;
		this.epayTaxPaymentInfo = epayTaxPaymentInfo;
		this.masterStatus = masterStatus;
		this.uuid = uuid;
		this.tranNo = tranNo;
		this.ctlCode = ctlCode;
		this.transmitDate = transmitDate;
		this.attachFile = attachFile;
		this.terminalId = terminalId;
		this.merchantId = merchantId;
		this.createBy = createBy;
		this.createDate = createDate;
		this.updateBy = updateBy;
		this.updateDate = updateDate;
		this.responseCode = responseCode;
		this.responseMessage = responseMessage;
		this.epayTaxPaymentInboundRefOutbounds = epayTaxPaymentInboundRefOutbounds;
	}

	@Id
	@SequenceGenerator(name="EPAY_TAX_PAYMENT_OUTBOUND_ID_SEQ", sequenceName="EPAY_TAX_PAYMENT_OUTBOUND_ID_SEQ", allocationSize=1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="EPAY_TAX_PAYMENT_OUTBOUND_ID_SEQ")
	@Column(name = "EPAY_TAX_PAYMENT_OUTBOUND_ID", unique = true, nullable = false)
	public long getEpayTaxPaymentOutboundId() {
		return this.epayTaxPaymentOutboundId;
	}

	public void setEpayTaxPaymentOutboundId(long epayTaxPaymentOutboundId) {
		this.epayTaxPaymentOutboundId = epayTaxPaymentOutboundId;
	}

	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EPAY_RECEIVER_PAYMENT_LINE_ID")
	public EpayReceiverPaymentLine getEpayReceiverPaymentLine() {
		return this.epayReceiverPaymentLine;
	}

	public void setEpayReceiverPaymentLine(EpayReceiverPaymentLine epayReceiverPaymentLine) {
		this.epayReceiverPaymentLine = epayReceiverPaymentLine;
	}

	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EPAY_TAX_PAYMENT_INFO_ID", nullable = false)
	public EpayTaxPaymentInfo getEpayTaxPaymentInfo() {
		return this.epayTaxPaymentInfo;
	}

	public void setEpayTaxPaymentInfo(EpayTaxPaymentInfo epayTaxPaymentInfo) {
		this.epayTaxPaymentInfo = epayTaxPaymentInfo;
	}

	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STATUS", nullable = false)
	public MasterStatus getMasterStatus() {
		return this.masterStatus;
	}

	public void setMasterStatus(MasterStatus masterStatus) {
		this.masterStatus = masterStatus;
	}

	@Column(name = "UUID", nullable = false, length = 36)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@Column(name = "TRAN_NO", length = 35)
	public String getTranNo() {
		return this.tranNo;
	}

	public void setTranNo(String tranNo) {
		this.tranNo = tranNo;
	}

	@Column(name = "CTL_CODE", length = 20)
	public String getCtlCode() {
		return this.ctlCode;
	}

	public void setCtlCode(String ctlCode) {
		this.ctlCode = ctlCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TRANSMIT_DATE", length = 26)
	public Date getTransmitDate() {
		return this.transmitDate;
	}

	public void setTransmitDate(Date transmitDate) {
		this.transmitDate = transmitDate;
	}

	@Column(name = "ATTACH_FILE", length = 400)
	public String getAttachFile() {
		return this.attachFile;
	}

	public void setAttachFile(String attachFile) {
		this.attachFile = attachFile;
	}

	@Column(name = "TERMINAL_ID", length = 20)
	public String getTerminalId() {
		return this.terminalId;
	}

	public void setTerminalId(String terminalId) {
		this.terminalId = terminalId;
	}

	@Column(name = "MERCHANT_ID", length = 20)
	public String getMerchantId() {
		return this.merchantId;
	}

	public void setMerchantId(String merchantId) {
		this.merchantId = merchantId;
	}

	@Column(name = "CREATE_BY", nullable = false, length = 20)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", nullable = false, length = 26)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "UPDATE_BY", nullable = false, length = 20)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DATE", nullable = false, length = 26)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "RESPONSE_CODE", length = 10)
	public String getResponseCode() {
		return this.responseCode;
	}

	public void setResponseCode(String responseCode) {
		this.responseCode = responseCode;
	}

	@Column(name = "RESPONSE_MESSAGE", length = 1000)
	public String getResponseMessage() {
		return this.responseMessage;
	}

	public void setResponseMessage(String responseMessage) {
		this.responseMessage = responseMessage;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "epayTaxPaymentOutbound",cascade = CascadeType.ALL)
	public List<EpayTaxPaymentInboundRefOutbound> getEpayTaxPaymentInboundRefOutbounds() {
		return this.epayTaxPaymentInboundRefOutbounds;
	}

	public void setEpayTaxPaymentInboundRefOutbounds(List<EpayTaxPaymentInboundRefOutbound> epayTaxPaymentInboundRefOutbounds) {
		this.epayTaxPaymentInboundRefOutbounds = epayTaxPaymentInboundRefOutbounds;
	}

}
