package th.go.rd.rdepaymentservice.entity;
// Generated Nov 16, 2018 5:16:31 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EpayTaxPaymentInfo generated by hbm2java
 */
@Entity
@Table(name = "EPAY_TAX_PAYMENT_INFO")
public class EpayTaxPaymentInfo implements java.io.Serializable {

	private long epayTaxPaymentInfoId;
	private EpayTaxPaymentInbound epayTaxPaymentInbound;
	private MasterStatus masterStatus;
	private String refNo;
	private String agentId;
	private Date expDate;
	private String recCode;
	private String paymentMethod;
	private String accountNo;
	private Date orderTranDate;
	private String createBy;
	private Date createDate;
	private String updateBy;
	private Date updateDate;
	private String taxMonthDisplay;
	private String agentBraNo;
	private String agentName;
	private Character isRound;
	private String formCodeDisplay;
	private BigDecimal taxAmount;
	private BigDecimal totalAmount;
	private BigDecimal criminalFinesAmount;
	private BigDecimal surchargeAmount;
	private String payLineCode;
	private BigDecimal netTaxAmount;
	private BigDecimal penaltyAmount;
	private BigDecimal totalTaxAmount;
	private List<EpayTaxPaymentInfoDetail> epayTaxPaymentInfoDetails = new ArrayList<>();
	private List<EpayTaxPaymentOutbound> epayTaxPaymentOutbounds = new ArrayList<>();
	private List<EpayKbankToken> epayKbankTokens = new ArrayList<>();

	public EpayTaxPaymentInfo() {
	}

	public EpayTaxPaymentInfo(long epayTaxPaymentInfoId, MasterStatus masterStatus, String refNo, String agentId, Date expDate, String paymentMethod, String createBy, Date createDate, String updateBy,
			Date updateDate, String agentBraNo, String agentName, String formCodeDisplay, BigDecimal totalAmount) {
		this.epayTaxPaymentInfoId = epayTaxPaymentInfoId;
		this.masterStatus = masterStatus;
		this.refNo = refNo;
		this.agentId = agentId;
		this.expDate = expDate;
		this.paymentMethod = paymentMethod;
		this.createBy = createBy;
		this.createDate = createDate;
		this.updateBy = updateBy;
		this.updateDate = updateDate;
		this.agentBraNo = agentBraNo;
		this.agentName = agentName;
		this.formCodeDisplay = formCodeDisplay;
		this.totalAmount = totalAmount;
	}
	public EpayTaxPaymentInfo(long epayTaxPaymentInfoId, EpayTaxPaymentInbound epayTaxPaymentInbound, MasterStatus masterStatus, String refNo, String agentId, Date expDate, String recCode,
			String paymentMethod, String accountNo, Date orderTranDate, String createBy, Date createDate, String updateBy, Date updateDate, String taxMonthDisplay, String agentBraNo, String agentName,
			Character isRound, String formCodeDisplay, BigDecimal taxAmount, BigDecimal totalAmount, BigDecimal criminalFinesAmount, BigDecimal surchargeAmount, String payLineCode,
			BigDecimal netTaxAmount, BigDecimal penaltyAmount, BigDecimal totalTaxAmount, List<EpayTaxPaymentInfoDetail> epayTaxPaymentInfoDetails, List<EpayTaxPaymentOutbound> epayTaxPaymentOutbounds,
			List<EpayKbankToken> epayKbankTokens) {
		this.epayTaxPaymentInfoId = epayTaxPaymentInfoId;
		this.epayTaxPaymentInbound = epayTaxPaymentInbound;
		this.masterStatus = masterStatus;
		this.refNo = refNo;
		this.agentId = agentId;
		this.expDate = expDate;
		this.recCode = recCode;
		this.paymentMethod = paymentMethod;
		this.accountNo = accountNo;
		this.orderTranDate = orderTranDate;
		this.createBy = createBy;
		this.createDate = createDate;
		this.updateBy = updateBy;
		this.updateDate = updateDate;
		this.taxMonthDisplay = taxMonthDisplay;
		this.agentBraNo = agentBraNo;
		this.agentName = agentName;
		this.isRound = isRound;
		this.formCodeDisplay = formCodeDisplay;
		this.taxAmount = taxAmount;
		this.totalAmount = totalAmount;
		this.criminalFinesAmount = criminalFinesAmount;
		this.surchargeAmount = surchargeAmount;
		this.payLineCode = payLineCode;
		this.netTaxAmount = netTaxAmount;
		this.penaltyAmount = penaltyAmount;
		this.totalTaxAmount = totalTaxAmount;
		this.epayTaxPaymentInfoDetails = epayTaxPaymentInfoDetails;
		this.epayTaxPaymentOutbounds = epayTaxPaymentOutbounds;
		this.epayKbankTokens = epayKbankTokens;
	}

	@Id
	@SequenceGenerator(name="EPAY_TAX_PAYMENT_INFO_ID_SEQ", sequenceName="EPAY_TAX_PAYMENT_INFO_ID_SEQ", allocationSize=1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="EPAY_TAX_PAYMENT_INFO_ID_SEQ")
	@Column(name = "EPAY_TAX_PAYMENT_INFO_ID", unique = true, nullable = false)
	public long getEpayTaxPaymentInfoId() {
		return this.epayTaxPaymentInfoId;
	}

	public void setEpayTaxPaymentInfoId(long epayTaxPaymentInfoId) {
		this.epayTaxPaymentInfoId = epayTaxPaymentInfoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EPAY_TAX_PAYMENT_INBOUND_ID")
	public EpayTaxPaymentInbound getEpayTaxPaymentInbound() {
		return this.epayTaxPaymentInbound;
	}

	public void setEpayTaxPaymentInbound(EpayTaxPaymentInbound epayTaxPaymentInbound) {
		this.epayTaxPaymentInbound = epayTaxPaymentInbound;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STATUS", nullable = false)
	public MasterStatus getMasterStatus() {
		return this.masterStatus;
	}

	public void setMasterStatus(MasterStatus masterStatus) {
		this.masterStatus = masterStatus;
	}

	@Column(name = "REF_NO", nullable = false, length = 20)
	public String getRefNo() {
		return this.refNo;
	}

	public void setRefNo(String refNo) {
		this.refNo = refNo;
	}

	@Column(name = "AGENT_ID", nullable = false, length = 20)
	public String getAgentId() {
		return this.agentId;
	}

	public void setAgentId(String agentId) {
		this.agentId = agentId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EXP_DATE", nullable = false, length = 26)
	public Date getExpDate() {
		return this.expDate;
	}

	public void setExpDate(Date expDate) {
		this.expDate = expDate;
	}

	@Column(name = "REC_CODE", length = 3)
	public String getRecCode() {
		return this.recCode;
	}

	public void setRecCode(String recCode) {
		this.recCode = recCode;
	}

	@Column(name = "PAYMENT_METHOD", nullable = false, length = 10)
	public String getPaymentMethod() {
		return this.paymentMethod;
	}

	public void setPaymentMethod(String paymentMethod) {
		this.paymentMethod = paymentMethod;
	}

	@Column(name = "ACCOUNT_NO", length = 20)
	public String getAccountNo() {
		return this.accountNo;
	}

	public void setAccountNo(String accountNo) {
		this.accountNo = accountNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ORDER_TRAN_DATE", length = 10)
	public Date getOrderTranDate() {
		return this.orderTranDate;
	}

	public void setOrderTranDate(Date orderTranDate) {
		this.orderTranDate = orderTranDate;
	}

	@Column(name = "CREATE_BY", nullable = false, length = 20)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", nullable = false, length = 26)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "UPDATE_BY", nullable = false, length = 20)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DATE", nullable = false, length = 26)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "TAX_MONTH_DISPLAY", length = 6)
	public String getTaxMonthDisplay() {
		return this.taxMonthDisplay;
	}

	public void setTaxMonthDisplay(String taxMonthDisplay) {
		this.taxMonthDisplay = taxMonthDisplay;
	}

	@Column(name = "AGENT_BRA_NO", nullable = false, length = 6)
	public String getAgentBraNo() {
		return this.agentBraNo;
	}

	public void setAgentBraNo(String agentBraNo) {
		this.agentBraNo = agentBraNo;
	}

	@Column(name = "AGENT_NAME", nullable = false, length = 400)
	public String getAgentName() {
		return this.agentName;
	}

	public void setAgentName(String agentName) {
		this.agentName = agentName;
	}

	@Column(name = "IS_ROUND", length = 1)
	public Character getIsRound() {
		return this.isRound;
	}

	public void setIsRound(Character isRound) {
		this.isRound = isRound;
	}

	@Column(name = "FORM_CODE_DISPLAY", nullable = false, length = 400)
	public String getFormCodeDisplay() {
		return this.formCodeDisplay;
	}

	public void setFormCodeDisplay(String formCodeDisplay) {
		this.formCodeDisplay = formCodeDisplay;
	}

	@Column(name = "TAX_AMOUNT", precision = 18)
	public BigDecimal getTaxAmount() {
		return this.taxAmount;
	}

	public void setTaxAmount(BigDecimal taxAmount) {
		this.taxAmount = taxAmount;
	}

	@Column(name = "TOTAL_AMOUNT", nullable = false, precision = 18)
	public BigDecimal getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(BigDecimal totalAmount) {
		this.totalAmount = totalAmount;
	}

	@Column(name = "CRIMINAL_FINES_AMOUNT", precision = 18)
	public BigDecimal getCriminalFinesAmount() {
		return this.criminalFinesAmount;
	}

	public void setCriminalFinesAmount(BigDecimal criminalFinesAmount) {
		this.criminalFinesAmount = criminalFinesAmount;
	}

	@Column(name = "SURCHARGE_AMOUNT", precision = 18)
	public BigDecimal getSurchargeAmount() {
		return this.surchargeAmount;
	}

	public void setSurchargeAmount(BigDecimal surchargeAmount) {
		this.surchargeAmount = surchargeAmount;
	}

	@Column(name = "PAY_LINE_CODE", length = 20)
	public String getPayLineCode() {
		return this.payLineCode;
	}

	public void setPayLineCode(String payLineCode) {
		this.payLineCode = payLineCode;
	}

	@Column(name = "NET_TAX_AMOUNT", precision = 18)
	public BigDecimal getNetTaxAmount() {
		return this.netTaxAmount;
	}

	public void setNetTaxAmount(BigDecimal netTaxAmount) {
		this.netTaxAmount = netTaxAmount;
	}

	@Column(name = "PENALTY_AMOUNT", precision = 18)
	public BigDecimal getPenaltyAmount() {
		return this.penaltyAmount;
	}

	public void setPenaltyAmount(BigDecimal penaltyAmount) {
		this.penaltyAmount = penaltyAmount;
	}

	@Column(name = "TOTAL_TAX_AMOUNT", precision = 18)
	public BigDecimal getTotalTaxAmount() {
		return this.totalTaxAmount;
	}

	public void setTotalTaxAmount(BigDecimal totalTaxAmount) {
		this.totalTaxAmount = totalTaxAmount;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "epayTaxPaymentInfo", cascade = CascadeType.ALL)
	public List<EpayTaxPaymentInfoDetail> getEpayTaxPaymentInfoDetails() {
		return this.epayTaxPaymentInfoDetails;
	}

	public void setEpayTaxPaymentInfoDetails(List<EpayTaxPaymentInfoDetail> epayTaxPaymentInfoDetails) {
		this.epayTaxPaymentInfoDetails = epayTaxPaymentInfoDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "epayTaxPaymentInfo", cascade = CascadeType.ALL)
	public List<EpayTaxPaymentOutbound> getEpayTaxPaymentOutbounds() {
		return this.epayTaxPaymentOutbounds;
	}

	public void setEpayTaxPaymentOutbounds(List<EpayTaxPaymentOutbound> epayTaxPaymentOutbounds) {
		this.epayTaxPaymentOutbounds = epayTaxPaymentOutbounds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "epayTaxPaymentInfo", cascade = CascadeType.ALL)
	public List<EpayKbankToken> getEpayKbankTokens() {
		return this.epayKbankTokens;
	}

	public void setEpayKbankTokens(List<EpayKbankToken> epayKbankTokens) {
		this.epayKbankTokens = epayKbankTokens;
	}

}
