package th.go.rd.rdepaymentservice.entity;
// Generated Jul 17, 2018 10:14:52 AM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * EpayTaxPaymentInbound generated by hbm2java
 */
@Entity
@Table(name = "EPAY_TAX_PAYMENT_INBOUND")
public class EpayTaxPaymentInbound implements java.io.Serializable {

	private long epayTaxPaymentInboundId;
	private EpayReceiverPaymentLine epayReceiverPaymentLine;
	private MasterPaymentStatus masterPaymentStatus;
	private MasterSendMethod masterSendMethod;
	private String rdTranNo;
	private String csTranNo;
	private String ref2;
	private String ref3;
	private String agentId;
	private String agentBraNo;
	private Date transferDate;
	private Date transmitDate;
	private BigDecimal totalAmount;
	private String terminalId;
	private String merchantId;
	private String payStatusMsg;
	private String attachFile;
	private String createBy;
	private Date createDate;
	private String updateBy;
	private Date updateDate;
	private String authorizeCode;
	private String responseCode;
	private String reponseMessage;
	private List<EpayTaxPaymentInfo> epayTaxPaymentInfos = new ArrayList<>();
	private List<EpayTaxPaymentInboundRefOutbound> epayTaxPaymentInboundRefOutbounds = new ArrayList<>();
	private List<EpayTaxPaymentInboundDetail> epayTaxPaymentInboundDetails = new ArrayList<>();
	private String uuid;

	public EpayTaxPaymentInbound() {
	}

	public EpayTaxPaymentInbound(long epayTaxPaymentInboundId, String rdTranNo, Date transmitDate, BigDecimal totalAmount, String createBy, Date createDate, String updateBy, Date updateDate) {
		this.epayTaxPaymentInboundId = epayTaxPaymentInboundId;
		this.rdTranNo = rdTranNo;
		this.transmitDate = transmitDate;
		this.totalAmount = totalAmount;
		this.createBy = createBy;
		this.createDate = createDate;
		this.updateBy = updateBy;
		this.updateDate = updateDate;
	}
	public EpayTaxPaymentInbound(long epayTaxPaymentInboundId, EpayReceiverPaymentLine epayReceiverPaymentLine, MasterPaymentStatus masterPaymentStatus, MasterSendMethod masterSendMethod,
			String rdTranNo, String csTranNo, String ref2, String ref3, String agentId, String agentBraNo, Date transferDate, Date transmitDate, BigDecimal totalAmount, String terminalId,
			String merchantId, String payStatusMsg, String attachFile, String createBy, Date createDate, String updateBy, Date updateDate, String authorizeCode, String responseCode,
			String reponseMessage, List<EpayTaxPaymentInfo> epayTaxPaymentInfos,List<EpayTaxPaymentInboundRefOutbound> epayTaxPaymentInboundRefOutbounds, List<EpayTaxPaymentInboundDetail> epayTaxPaymentInboundDetails, String uuid) {
		this.epayTaxPaymentInboundId = epayTaxPaymentInboundId;
		this.epayReceiverPaymentLine = epayReceiverPaymentLine;
		this.masterPaymentStatus = masterPaymentStatus;
		this.masterSendMethod = masterSendMethod;
		this.rdTranNo = rdTranNo;
		this.csTranNo = csTranNo;
		this.ref2 = ref2;
		this.ref3 = ref3;
		this.agentId = agentId;
		this.agentBraNo = agentBraNo;
		this.transferDate = transferDate;
		this.transmitDate = transmitDate;
		this.totalAmount = totalAmount;
		this.terminalId = terminalId;
		this.merchantId = merchantId;
		this.payStatusMsg = payStatusMsg;
		this.attachFile = attachFile;
		this.createBy = createBy;
		this.createDate = createDate;
		this.updateBy = updateBy;
		this.updateDate = updateDate;
		this.authorizeCode = authorizeCode;
		this.responseCode = responseCode;
		this.reponseMessage = reponseMessage;
		this.epayTaxPaymentInfos = epayTaxPaymentInfos;
		this.epayTaxPaymentInboundRefOutbounds = epayTaxPaymentInboundRefOutbounds;
		this.epayTaxPaymentInboundDetails = epayTaxPaymentInboundDetails;
		this.uuid = uuid;
	}

	@Id
	@SequenceGenerator(name="EPAY_TAX_PAYMENT_INBOUND_ID_SEQ", sequenceName="EPAY_TAX_PAYMENT_INBOUND_ID_SEQ", allocationSize=1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="EPAY_TAX_PAYMENT_INBOUND_ID_SEQ")
	@Column(name = "EPAY_TAX_PAYMENT_INBOUND_ID", unique = true, nullable = false)
	public long getEpayTaxPaymentInboundId() {
		return this.epayTaxPaymentInboundId;
	}

	public void setEpayTaxPaymentInboundId(long epayTaxPaymentInboundId) {
		this.epayTaxPaymentInboundId = epayTaxPaymentInboundId;
	}

	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EPAY_RECEIVER_PAYMENT_LINE_ID")
	public EpayReceiverPaymentLine getEpayReceiverPaymentLine() {
		return this.epayReceiverPaymentLine;
	}

	public void setEpayReceiverPaymentLine(EpayReceiverPaymentLine epayReceiverPaymentLine) {
		this.epayReceiverPaymentLine = epayReceiverPaymentLine;
	}

	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PAY_STATUS")
	public MasterPaymentStatus getMasterPaymentStatus() {
		return this.masterPaymentStatus;
	}

	public void setMasterPaymentStatus(MasterPaymentStatus masterPaymentStatus) {
		this.masterPaymentStatus = masterPaymentStatus;
	}

	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SEND_METHOD")
	public MasterSendMethod getMasterSendMethod() {
		return this.masterSendMethod;
	}

	public void setMasterSendMethod(MasterSendMethod masterSendMethod) {
		this.masterSendMethod = masterSendMethod;
	}

	@Column(name = "RD_TRAN_NO", length = 35)
	public String getRdTranNo() {
		return this.rdTranNo;
	}

	public void setRdTranNo(String rdTranNo) {
		this.rdTranNo = rdTranNo;
	}

	@Column(name = "CS_TRAN_NO",length = 35)
	public String getCsTranNo() {
		return this.csTranNo;
	}

	public void setCsTranNo(String csTranNo) {
		this.csTranNo = csTranNo;
	}

	@Column(name = "REF2", length = 20)
	public String getRef2() {
		return this.ref2;
	}

	public void setRef2(String ref2) {
		this.ref2 = ref2;
	}

	@Column(name = "REF3", length = 20)
	public String getRef3() {
		return this.ref3;
	}

	public void setRef3(String ref3) {
		this.ref3 = ref3;
	}

	@Column(name = "AGENT_ID", length = 20)
	public String getAgentId() {
		return this.agentId;
	}

	public void setAgentId(String agentId) {
		this.agentId = agentId;
	}

	@Column(name = "AGENT_BRA_NO", length = 6)
	public String getAgentBraNo() {
		return this.agentBraNo;
	}

	public void setAgentBraNo(String agentBraNo) {
		this.agentBraNo = agentBraNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TRANSFER_DATE", length = 26)
	public Date getTransferDate() {
		return this.transferDate;
	}

	public void setTransferDate(Date transferDate) {
		this.transferDate = transferDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TRANSMIT_DATE", nullable = false, length = 26)
	public Date getTransmitDate() {
		return this.transmitDate;
	}

	public void setTransmitDate(Date transmitDate) {
		this.transmitDate = transmitDate;
	}

	@Column(name = "TOTAL_AMOUNT", nullable = false, precision = 16)
	public BigDecimal getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(BigDecimal totalAmount) {
		this.totalAmount = totalAmount;
	}

	@Column(name = "TERMINAL_ID", length = 20)
	public String getTerminalId() {
		return this.terminalId;
	}

	public void setTerminalId(String terminalId) {
		this.terminalId = terminalId;
	}

	@Column(name = "MERCHANT_ID", length = 20)
	public String getMerchantId() {
		return this.merchantId;
	}

	public void setMerchantId(String merchantId) {
		this.merchantId = merchantId;
	}

	@Column(name = "PAY_STATUS_MSG", length = 400)
	public String getPayStatusMsg() {
		return this.payStatusMsg;
	}

	public void setPayStatusMsg(String payStatusMsg) {
		this.payStatusMsg = payStatusMsg;
	}

	@Column(name = "ATTACH_FILE", length = 400)
	public String getAttachFile() {
		return this.attachFile;
	}

	public void setAttachFile(String attachFile) {
		this.attachFile = attachFile;
	}

	@Column(name = "CREATE_BY", nullable = false, length = 20)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", nullable = false, length = 26)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "UPDATE_BY", nullable = false, length = 20)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DATE", nullable = false, length = 26)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "AUTHORIZE_CODE", length = 40)
	public String getAuthorizeCode() {
		return this.authorizeCode;
	}

	public void setAuthorizeCode(String authorizeCode) {
		this.authorizeCode = authorizeCode;
	}

	@Column(name = "RESPONSE_CODE", length = 10)
	public String getResponseCode() {
		return this.responseCode;
	}

	public void setResponseCode(String responseCode) {
		this.responseCode = responseCode;
	}

	@Column(name = "REPONSE_MESSAGE", length = 1000)
	public String getReponseMessage() {
		return this.reponseMessage;
	}

	public void setReponseMessage(String reponseMessage) {
		this.reponseMessage = reponseMessage;
	}

	@JsonManagedReference
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "epayTaxPaymentInbound")
	public List<EpayTaxPaymentInfo> getEpayTaxPaymentInfos() {
		return this.epayTaxPaymentInfos;
	}

	public void setEpayTaxPaymentInfos(List<EpayTaxPaymentInfo> epayTaxPaymentInfos) {
		this.epayTaxPaymentInfos = epayTaxPaymentInfos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "epayTaxPaymentInbound",cascade = CascadeType.ALL)
	public List<EpayTaxPaymentInboundRefOutbound> getEpayTaxPaymentInboundRefOutbounds() {
		return this.epayTaxPaymentInboundRefOutbounds;
	}

	public void setEpayTaxPaymentInboundRefOutbounds(List<EpayTaxPaymentInboundRefOutbound> epayTaxPaymentInboundRefOutbounds) {
		this.epayTaxPaymentInboundRefOutbounds = epayTaxPaymentInboundRefOutbounds;
	}

	@JsonManagedReference
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "epayTaxPaymentInbound",cascade = CascadeType.ALL)
	public List<EpayTaxPaymentInboundDetail> getEpayTaxPaymentInboundDetails() {
		return this.epayTaxPaymentInboundDetails;
	}

	public void setEpayTaxPaymentInboundDetails(List<EpayTaxPaymentInboundDetail> epayTaxPaymentInboundDetails) {
		this.epayTaxPaymentInboundDetails = epayTaxPaymentInboundDetails;
	}

	@Column(name = "UUID", nullable = false, length = 36)
	public String getUuid() {
		return uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

}
