package th.go.rd.rdepaymentservice.entity;
// Generated Jul 17, 2018 10:14:52 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * EpayRolePermission generated by hbm2java
 */
@Entity
@Table(name = "EPAY_ROLE_PERMISSION")
public class EpayRolePermission implements java.io.Serializable {

	private long epayRolePermissionId;
	private EpayAuthorization epayAuthorization;
	private MasterSystemInfo masterSystemInfo;
	private String createBy;
	private Date createDate;
	private String updateBy;
	private Date updateDate;

	public EpayRolePermission() {
	}

	public EpayRolePermission(long epayRolePermissionId, EpayAuthorization epayAuthorization, MasterSystemInfo masterSystemInfo, String createBy, Date createDate, String updateBy, Date updateDate) {
		this.epayRolePermissionId = epayRolePermissionId;
		this.epayAuthorization = epayAuthorization;
		this.masterSystemInfo = masterSystemInfo;
		this.createBy = createBy;
		this.createDate = createDate;
		this.updateBy = updateBy;
		this.updateDate = updateDate;
	}

	@Id
	@SequenceGenerator(name="EPAY_ROLE_PERMISSION_ID_SEQ", sequenceName="EPAY_ROLE_PERMISSION_ID_SEQ", allocationSize=1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="EPAY_ROLE_PERMISSION_ID_SEQ")
	@Column(name = "EPAY_ROLE_PERMISSION_ID", unique = true, nullable = false)
	public long getEpayRolePermissionId() {
		return this.epayRolePermissionId;
	}

	public void setEpayRolePermissionId(long epayRolePermissionId) {
		this.epayRolePermissionId = epayRolePermissionId;
	}

	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EPAY_AUTHORIZATION_ID", nullable = false)
	public EpayAuthorization getEpayAuthorization() {
		return this.epayAuthorization;
	}

	public void setEpayAuthorization(EpayAuthorization epayAuthorization) {
		this.epayAuthorization = epayAuthorization;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MASTER_SYSTEM_INFO_ID", nullable = false)
	public MasterSystemInfo getMasterSystemInfo() {
		return this.masterSystemInfo;
	}

	public void setMasterSystemInfo(MasterSystemInfo masterSystemInfo) {
		this.masterSystemInfo = masterSystemInfo;
	}

	@Column(name = "CREATE_BY", nullable = false, length = 20)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", nullable = false, length = 26)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "UPDATE_BY", nullable = false, length = 20)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DATE", nullable = false, length = 26)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
