package th.go.rd.rdepaymentservice.entity;
// Generated Jul 17, 2018 10:14:52 AM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * EpayTaxPaymentInboundDetail generated by hbm2java
 */
@Entity
@Table(name = "EPAY_TAX_PAYMENT_INBOUND_DETAIL")
public class EpayTaxPaymentInboundDetail implements java.io.Serializable {

	private int epayTaxPaymentInboundDetailId;
	private EpayTaxPaymentInbound epayTaxPaymentInbound;
	private String sysRefNo;
	private BigDecimal amount;
	private String nid;
	private String nidBraNo;
	private String createBy;
	private Date createDate;
	private String updateBy;
	private Date updateDate;

	public EpayTaxPaymentInboundDetail() {
	}

	public EpayTaxPaymentInboundDetail(int epayTaxPaymentInboundDetailId, EpayTaxPaymentInbound epayTaxPaymentInbound, String sysRefNo, BigDecimal amount, String nid, String nidBraNo, String createBy,
			Date createDate, String updateBy, Date updateDate) {
		this.epayTaxPaymentInboundDetailId = epayTaxPaymentInboundDetailId;
		this.epayTaxPaymentInbound = epayTaxPaymentInbound;
		this.sysRefNo = sysRefNo;
		this.amount = amount;
		this.nid = nid;
		this.nidBraNo = nidBraNo;
		this.createBy = createBy;
		this.createDate = createDate;
		this.updateBy = updateBy;
		this.updateDate = updateDate;
	}

	@Id
	@SequenceGenerator(name="EPAY_TAX_PAYMENT_INBOUND_DETAIL_ID_SEQ", sequenceName="EPAY_TAX_PAYMENT_INBOUND_DETAIL_ID_SEQ", allocationSize=1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="EPAY_TAX_PAYMENT_INBOUND_DETAIL_ID_SEQ")
	@Column(name = "EPAY_TAX_PAYMENT_INBOUND_DETAIL_ID", unique = true, nullable = false)
	public int getEpayTaxPaymentInboundDetailId() {
		return this.epayTaxPaymentInboundDetailId;
	}

	public void setEpayTaxPaymentInboundDetailId(int epayTaxPaymentInboundDetailId) {
		this.epayTaxPaymentInboundDetailId = epayTaxPaymentInboundDetailId;
	}

	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EPAY_TAX_PAYMENT_INBOUND_ID", nullable = false)
	public EpayTaxPaymentInbound getEpayTaxPaymentInbound() {
		return this.epayTaxPaymentInbound;
	}

	public void setEpayTaxPaymentInbound(EpayTaxPaymentInbound epayTaxPaymentInbound) {
		this.epayTaxPaymentInbound = epayTaxPaymentInbound;
	}

	@Column(name = "SYS_REF_NO", nullable = false, length = 20)
	public String getSysRefNo() {
		return this.sysRefNo;
	}

	public void setSysRefNo(String sysRefNo) {
		this.sysRefNo = sysRefNo;
	}

	@Column(name = "AMOUNT", nullable = false, precision = 18)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "NID", nullable = false, length = 13)
	public String getNid() {
		return this.nid;
	}

	public void setNid(String nid) {
		this.nid = nid;
	}

	@Column(name = "NID_BRA_NO", nullable = false, length = 6)
	public String getNidBraNo() {
		return this.nidBraNo;
	}

	public void setNidBraNo(String nidBraNo) {
		this.nidBraNo = nidBraNo;
	}

	@Column(name = "CREATE_BY", nullable = false, length = 20)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", nullable = false, length = 26)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "UPDATE_BY", nullable = false, length = 20)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DATE", nullable = false, length = 26)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
