package th.go.rd.rdepaymentservice.entity;
// Generated Jul 17, 2018 10:14:52 AM by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * EpayAuthorization generated by hbm2java
 */
@Entity
@Table(name = "EPAY_AUTHORIZATION")
public class EpayAuthorization implements java.io.Serializable {

	private long epayAuthorizationId;
	private MasterStatus masterStatus;
	private String authCode;
	private String description;
	private String createBy;
	private Date createDate;
	private String updateBy;
	private Date updateDate;
	private List<EpayRolePermission> epayRolePermissions = new ArrayList<>();

	public EpayAuthorization() {
	}

	public EpayAuthorization(long epayAuthorizationId, MasterStatus masterStatus, String authCode, String createBy, Date createDate, String updateBy, Date updateDate) {
		this.epayAuthorizationId = epayAuthorizationId;
		this.masterStatus = masterStatus;
		this.authCode = authCode;
		this.createBy = createBy;
		this.createDate = createDate;
		this.updateBy = updateBy;
		this.updateDate = updateDate;
	}
	public EpayAuthorization(long epayAuthorizationId, MasterStatus masterStatus, String authCode, String description, String createBy, Date createDate, String updateBy, Date updateDate,
			List<EpayRolePermission> epayRolePermissions) {
		this.epayAuthorizationId = epayAuthorizationId;
		this.masterStatus = masterStatus;
		this.authCode = authCode;
		this.description = description;
		this.createBy = createBy;
		this.createDate = createDate;
		this.updateBy = updateBy;
		this.updateDate = updateDate;
		this.epayRolePermissions = epayRolePermissions;
	}

	@Id
	@SequenceGenerator(name="EPAY_AUTHORIZATION_ID_SEQ", sequenceName="EPAY_AUTHORIZATION_ID_SEQ", allocationSize=1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="EPAY_AUTHORIZATION_ID_SEQ")
	@Column(name = "EPAY_AUTHORIZATION_ID", unique = true, nullable = false)
	public long getEpayAuthorizationId() {
		return this.epayAuthorizationId;
	}

	public void setEpayAuthorizationId(long epayAuthorizationId) {
		this.epayAuthorizationId = epayAuthorizationId;
	}

	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STATUS", nullable = false)
	public MasterStatus getMasterStatus() {
		return this.masterStatus;
	}

	public void setMasterStatus(MasterStatus masterStatus) {
		this.masterStatus = masterStatus;
	}

	@Column(name = "AUTH_CODE", nullable = false, length = 60)
	public String getAuthCode() {
		return this.authCode;
	}

	public void setAuthCode(String authCode) {
		this.authCode = authCode;
	}

	@Column(name = "DESCRIPTION", length = 400)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "CREATE_BY", nullable = false, length = 20)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", nullable = false, length = 26)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "UPDATE_BY", nullable = false, length = 20)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DATE", nullable = false, length = 26)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}
	@JsonBackReference
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "epayAuthorization",cascade = CascadeType.ALL, orphanRemoval = true)
	public List<EpayRolePermission> getEpayRolePermissions() {
		return this.epayRolePermissions;
	}

	public void setEpayRolePermissions(List<EpayRolePermission> epayRolePermissions) {
		this.epayRolePermissions = epayRolePermissions;
	}

}
