package th.go.rd.rdepaymentservice.entity;
// Generated Sep 10, 2018 11:15:37 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EpayReceiverPaymentLineApiUrl generated by hbm2java
 */
@Entity
@Table(name = "EPAY_RECEIVER_PAYMENT_LINE_API_URL")
public class EpayReceiverPaymentLineApiUrl implements java.io.Serializable {

	private int epayReceiverPaymentLineApiUrlId;
	private EpayReceiverPaymentLine epayReceiverPaymentLine;
	private MasterStatus masterStatus;
	private String apiUrl;
	private String description;
	private String createBy;
	private Date createDate;
	private String updateBy;
	private Date updateDate;

	public EpayReceiverPaymentLineApiUrl() {
	}

	public EpayReceiverPaymentLineApiUrl(int epayReceiverPaymentLineApiUrlId, EpayReceiverPaymentLine epayReceiverPaymentLine, MasterStatus masterStatus, String apiUrl, String createBy,
			Date createDate, String updateBy, Date updateDate) {
		this.epayReceiverPaymentLineApiUrlId = epayReceiverPaymentLineApiUrlId;
		this.epayReceiverPaymentLine = epayReceiverPaymentLine;
		this.masterStatus = masterStatus;
		this.apiUrl = apiUrl;
		this.createBy = createBy;
		this.createDate = createDate;
		this.updateBy = updateBy;
		this.updateDate = updateDate;
	}
	public EpayReceiverPaymentLineApiUrl(int epayReceiverPaymentLineApiUrlId, EpayReceiverPaymentLine epayReceiverPaymentLine, MasterStatus masterStatus, String apiUrl, String description,
			String createBy, Date createDate, String updateBy, Date updateDate) {
		this.epayReceiverPaymentLineApiUrlId = epayReceiverPaymentLineApiUrlId;
		this.epayReceiverPaymentLine = epayReceiverPaymentLine;
		this.masterStatus = masterStatus;
		this.apiUrl = apiUrl;
		this.description = description;
		this.createBy = createBy;
		this.createDate = createDate;
		this.updateBy = updateBy;
		this.updateDate = updateDate;
	}

	@Id
	@SequenceGenerator(name="EPAY_RECEIVER_PAYMENT_LINE_API_URL_SEQ", sequenceName="EPAY_RECEIVER_PAYMENT_LINE_API_URL_SEQ", allocationSize=1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="EPAY_RECEIVER_PAYMENT_LINE_API_URL_SEQ")
	@Column(name = "EPAY_RECEIVER_PAYMENT_LINE_API_URL_ID", unique = true, nullable = false)
	public int getEpayReceiverPaymentLineApiUrlId() {
		return this.epayReceiverPaymentLineApiUrlId;
	}

	public void setEpayReceiverPaymentLineApiUrlId(int epayReceiverPaymentLineApiUrlId) {
		this.epayReceiverPaymentLineApiUrlId = epayReceiverPaymentLineApiUrlId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EPAY_RECEIVER_PAYMENT_LINE_ID", nullable = false)
	public EpayReceiverPaymentLine getEpayReceiverPaymentLine() {
		return this.epayReceiverPaymentLine;
	}

	public void setEpayReceiverPaymentLine(EpayReceiverPaymentLine epayReceiverPaymentLine) {
		this.epayReceiverPaymentLine = epayReceiverPaymentLine;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STATUS", nullable = false)
	public MasterStatus getMasterStatus() {
		return this.masterStatus;
	}

	public void setMasterStatus(MasterStatus masterStatus) {
		this.masterStatus = masterStatus;
	}

	@Column(name = "API_URL", nullable = false, length = 1000)
	public String getApiUrl() {
		return this.apiUrl;
	}

	public void setApiUrl(String apiUrl) {
		this.apiUrl = apiUrl;
	}

	@Column(name = "DESCRIPTION", length = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "CREATE_BY", nullable = false, length = 20)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", nullable = false, length = 26)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "UPDATE_BY", nullable = false, length = 20)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DATE", nullable = false, length = 26)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
