package th.go.rd.rdepaymentservice.entity;
// Generated Jul 17, 2018 10:14:52 AM by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * MasterSendMethod generated by hbm2java
 */
@Entity
@Table(name = "MASTER_SEND_METHOD")
public class MasterSendMethod implements java.io.Serializable {

	private String sendMethod;
	private String description;
	private List<EpayTaxPaymentInbound> epayTaxPaymentInbounds = new ArrayList<>();

	public MasterSendMethod() {
	}

	public MasterSendMethod(String sendMethod) {
		this.sendMethod = sendMethod;
	}
	public MasterSendMethod(String sendMethod, String description, List<EpayTaxPaymentInbound> epayTaxPaymentInbounds) {
		this.sendMethod = sendMethod;
		this.description = description;
		this.epayTaxPaymentInbounds = epayTaxPaymentInbounds;
	}

	@Id

	@Column(name = "SEND_METHOD", unique = true, nullable = false, length = 10)
	public String getSendMethod() {
		return this.sendMethod;
	}

	public void setSendMethod(String sendMethod) {
		this.sendMethod = sendMethod;
	}

	@Column(name = "DESCRIPTION", length = 400)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@JsonManagedReference
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "masterSendMethod",cascade=CascadeType.ALL)
	public List<EpayTaxPaymentInbound> getEpayTaxPaymentInbounds() {
		return this.epayTaxPaymentInbounds;
	}

	public void setEpayTaxPaymentInbounds(List<EpayTaxPaymentInbound> epayTaxPaymentInbounds) {
		this.epayTaxPaymentInbounds = epayTaxPaymentInbounds;
	}

}
