package th.go.rd.rdepaymentservice.entity;
// Generated Jul 17, 2018 10:14:52 AM by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * MasterPaymentLine generated by hbm2java
 */
@Entity
@Table(name = "MASTER_PAYMENT_LINE")
public class MasterPaymentLine implements java.io.Serializable {

	private long masterPaymentLineId;
	private MasterStatus masterStatus;
	private String payLineCode;
	private String payLineNameTh;
	private String payLineNameEn;
	private String createBy;
	private Date createDate;
	private String updateBy;
	private Date updateDate;
	private List<EpayReceiverPaymentLine> epayReceiverPaymentLines = new ArrayList<>();

	public MasterPaymentLine() {
	}

	public MasterPaymentLine(long masterPaymentLineId, MasterStatus masterStatus, String payLineCode, String payLineNameTh, String payLineNameEn, String createBy, Date createDate, String updateBy,
			Date updateDate) {
		this.masterPaymentLineId = masterPaymentLineId;
		this.masterStatus = masterStatus;
		this.payLineCode = payLineCode;
		this.payLineNameTh = payLineNameTh;
		this.payLineNameEn = payLineNameEn;
		this.createBy = createBy;
		this.createDate = createDate;
		this.updateBy = updateBy;
		this.updateDate = updateDate;
	}
	public MasterPaymentLine(long masterPaymentLineId, MasterStatus masterStatus, String payLineCode, String payLineNameTh, String payLineNameEn, String createBy, Date createDate, String updateBy,
			Date updateDate, List<EpayReceiverPaymentLine> epayReceiverPaymentLines) {
		this.masterPaymentLineId = masterPaymentLineId;
		this.masterStatus = masterStatus;
		this.payLineCode = payLineCode;
		this.payLineNameTh = payLineNameTh;
		this.payLineNameEn = payLineNameEn;
		this.createBy = createBy;
		this.createDate = createDate;
		this.updateBy = updateBy;
		this.updateDate = updateDate;
		this.epayReceiverPaymentLines = epayReceiverPaymentLines;
	}

	@Id
	@SequenceGenerator(name="MASTER_PAYMENT_LINE_ID_SEQ", sequenceName="MASTER_PAYMENT_LINE_ID_SEQ", allocationSize=1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="MASTER_PAYMENT_LINE_ID_SEQ")
	@Column(name = "MASTER_PAYMENT_LINE_ID", unique = true, nullable = false)
	public long getMasterPaymentLineId() {
		return this.masterPaymentLineId;
	}

	public void setMasterPaymentLineId(long masterPaymentLineId) {
		this.masterPaymentLineId = masterPaymentLineId;
	}

	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STATUS", nullable = false)
	public MasterStatus getMasterStatus() {
		return this.masterStatus;
	}

	public void setMasterStatus(MasterStatus masterStatus) {
		this.masterStatus = masterStatus;
	}

	@Column(name = "PAY_LINE_CODE", nullable = false, length = 10)
	public String getPayLineCode() {
		return this.payLineCode;
	}

	public void setPayLineCode(String payLineCode) {
		this.payLineCode = payLineCode;
	}

	@Column(name = "PAY_LINE_NAME_TH", nullable = false, length = 200)
	public String getPayLineNameTh() {
		return this.payLineNameTh;
	}

	public void setPayLineNameTh(String payLineNameTh) {
		this.payLineNameTh = payLineNameTh;
	}

	@Column(name = "PAY_LINE_NAME_EN", nullable = false, length = 200)
	public String getPayLineNameEn() {
		return this.payLineNameEn;
	}

	public void setPayLineNameEn(String payLineNameEn) {
		this.payLineNameEn = payLineNameEn;
	}

	@Column(name = "CREATE_BY", nullable = false, length = 20)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", nullable = false, length = 26)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "UPDATE_BY", nullable = false, length = 20)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DATE", nullable = false, length = 26)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@JsonManagedReference
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "masterPaymentLine",cascade=CascadeType.ALL)
	public List<EpayReceiverPaymentLine> getEpayReceiverPaymentLines() {
		return this.epayReceiverPaymentLines;
	}

	public void setEpayReceiverPaymentLines(List<EpayReceiverPaymentLine> epayReceiverPaymentLines) {
		this.epayReceiverPaymentLines = epayReceiverPaymentLines;
	}

}
