package th.go.rd.rdepaymentservice.entity;
// Generated Aug 24, 2018 10:17:14 AM by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * MasterSystemInfo generated by hbm2java
 */
@Entity
@Table(name = "MASTER_SYSTEM_INFO", uniqueConstraints = @UniqueConstraint(columnNames = "CLIENT_ID"))
public class MasterSystemInfo implements java.io.Serializable {

	private int masterSystemInfoId;
	private MasterStatus masterStatus;
	private String systemCode;
	private String systemName;
	private String description;
	private String clientId;
	private String secretId;
	private String createBy;
	private Date createDate;
	private String updateBy;
	private Date updateDate;
	private List<EpayRolePermission> epayRolePermissions = new ArrayList<>();

	public MasterSystemInfo() {
	}

	public MasterSystemInfo(int masterSystemInfoId, MasterStatus masterStatus, String systemCode, String systemName, String clientId, String secretId, String createBy, Date createDate,
			String updateBy, Date updateDate) {
		this.masterSystemInfoId = masterSystemInfoId;
		this.masterStatus = masterStatus;
		this.systemCode = systemCode;
		this.systemName = systemName;
		this.clientId = clientId;
		this.secretId = secretId;
		this.createBy = createBy;
		this.createDate = createDate;
		this.updateBy = updateBy;
		this.updateDate = updateDate;
	}
	public MasterSystemInfo(int masterSystemInfoId, MasterStatus masterStatus, String systemCode, String systemName, String description, String clientId, String secretId, String createBy,
			Date createDate, String updateBy, Date updateDate, List<EpayRolePermission> epayRolePermissions) {
		this.masterSystemInfoId = masterSystemInfoId;
		this.masterStatus = masterStatus;
		this.systemCode = systemCode;
		this.systemName = systemName;
		this.description = description;
		this.clientId = clientId;
		this.secretId = secretId;
		this.createBy = createBy;
		this.createDate = createDate;
		this.updateBy = updateBy;
		this.updateDate = updateDate;
		this.epayRolePermissions = epayRolePermissions;
	}

	@Id
	@SequenceGenerator(name="MASTER_SYSTEM_INFO_SEQ", sequenceName="MASTER_SYSTEM_INFO_SEQ", allocationSize=1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="MASTER_SYSTEM_INFO_SEQ")
	@Column(name = "MASTER_SYSTEM_INFO_ID", unique = true, nullable = false)
	public int getMasterSystemInfoId() {
		return this.masterSystemInfoId;
	}

	public void setMasterSystemInfoId(int masterSystemInfoId) {
		this.masterSystemInfoId = masterSystemInfoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STATUS", nullable = false)
	public MasterStatus getMasterStatus() {
		return this.masterStatus;
	}

	public void setMasterStatus(MasterStatus masterStatus) {
		this.masterStatus = masterStatus;
	}

	@Column(name = "SYSTEM_CODE", nullable = false, length = 100)
	public String getSystemCode() {
		return this.systemCode;
	}

	public void setSystemCode(String systemCode) {
		this.systemCode = systemCode;
	}

	@Column(name = "SYSTEM_NAME", nullable = false, length = 400)
	public String getSystemName() {
		return this.systemName;
	}

	public void setSystemName(String systemName) {
		this.systemName = systemName;
	}

	@Column(name = "DESCRIPTION", length = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "CLIENT_ID", unique = true, nullable = false, length = 100)
	public String getClientId() {
		return this.clientId;
	}

	public void setClientId(String clientId) {
		this.clientId = clientId;
	}

	@Column(name = "SECRET_ID", nullable = false, length = 100)
	public String getSecretId() {
		return this.secretId;
	}

	public void setSecretId(String secretId) {
		this.secretId = secretId;
	}

	@Column(name = "CREATE_BY", nullable = false, length = 20)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", nullable = false, length = 26)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "UPDATE_BY", nullable = false, length = 20)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DATE", nullable = false, length = 26)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "masterSystemInfo")
	public List<EpayRolePermission> getEpayRolePermissions() {
		return this.epayRolePermissions;
	}

	public void setEpayRolePermissions(List<EpayRolePermission> epayRolePermissions) {
		this.epayRolePermissions = epayRolePermissions;
	}

}
