package th.go.rd.rdepaymentservice.entity;
// Generated Nov 15, 2018 3:18:13 PM by Hibernate Tools 4.3.5.Final

import java.sql.Blob;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * MasterReceiverUnit generated by hbm2java
 */
@Entity
@Table(name = "MASTER_RECEIVER_UNIT")
public class MasterReceiverUnit implements java.io.Serializable {

	private long masterReceiverUnitId;
	private MasterReceiverType masterReceiverType;
	private MasterStatus masterStatus;
	private String recCode;
	private String recShortNameTh;
	private String recShortNameEn;
	private String recNameTh;
	private String recNameEn;
	private String createBy;
	private Date createDate;
	private String updateBy;
	private Date updateDate;
	private Integer recFileNo;
	private Blob imagePath;
	private List<EpayReceiverPaymentLine> epayReceiverPaymentLines = new ArrayList<>();

	public MasterReceiverUnit() {
	}

	public MasterReceiverUnit(long masterReceiverUnitId, MasterReceiverType masterReceiverType, MasterStatus masterStatus, String recCode, String recShortNameTh, String recShortNameEn, String recNameTh, String recNameEn,
			String createBy, Date createDate, String updateBy, Date updateDate) {
		this.masterReceiverUnitId = masterReceiverUnitId;
		this.masterReceiverType = masterReceiverType;
		this.masterStatus = masterStatus;
		this.recCode = recCode;
		this.recShortNameTh = recShortNameTh;
		this.recShortNameEn = recShortNameEn;
		this.recNameTh = recNameTh;
		this.recNameEn = recNameEn;
		this.createBy = createBy;
		this.createDate = createDate;
		this.updateBy = updateBy;
		this.updateDate = updateDate;
	}
	public MasterReceiverUnit(long masterReceiverUnitId, MasterReceiverType masterReceiverType, MasterStatus masterStatus, String recCode, String recShortNameTh, String recShortNameEn, String recNameTh, String recNameEn,
			String createBy, Date createDate, String updateBy, Date updateDate, Integer recFileNo, Blob imagePath, List<EpayReceiverPaymentLine> epayReceiverPaymentLines) {
		this.masterReceiverUnitId = masterReceiverUnitId;
		this.masterReceiverType = masterReceiverType;
		this.masterStatus = masterStatus;
		this.recCode = recCode;
		this.recShortNameTh = recShortNameTh;
		this.recShortNameEn = recShortNameEn;
		this.recNameTh = recNameTh;
		this.recNameEn = recNameEn;
		this.createBy = createBy;
		this.createDate = createDate;
		this.updateBy = updateBy;
		this.updateDate = updateDate;
		this.recFileNo = recFileNo;
		this.imagePath = imagePath;
		this.epayReceiverPaymentLines = epayReceiverPaymentLines;
	}

	@Id
	@SequenceGenerator(name="MASTER_RECEIVER_UNIT_ID_SEQ", sequenceName="MASTER_RECEIVER_UNIT_ID_SEQ", allocationSize=1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="MASTER_RECEIVER_UNIT_ID_SEQ")
	@Column(name = "MASTER_RECEIVER_UNIT_ID", unique = true, nullable = false)
	public long getMasterReceiverUnitId() {
		return this.masterReceiverUnitId;
	}

	public void setMasterReceiverUnitId(long masterReceiverUnitId) {
		this.masterReceiverUnitId = masterReceiverUnitId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REC_TYPE", nullable = false)
	public MasterReceiverType getMasterReceiverType() {
		return this.masterReceiverType;
	}

	public void setMasterReceiverType(MasterReceiverType masterReceiverType) {
		this.masterReceiverType = masterReceiverType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STATUS", nullable = false)
	public MasterStatus getMasterStatus() {
		return this.masterStatus;
	}

	public void setMasterStatus(MasterStatus masterStatus) {
		this.masterStatus = masterStatus;
	}

	@Column(name = "REC_CODE", nullable = false, length = 3)
	public String getRecCode() {
		return this.recCode;
	}

	public void setRecCode(String recCode) {
		this.recCode = recCode;
	}

	@Column(name = "REC_SHORT_NAME_TH", nullable = false, length = 100)
	public String getRecShortNameTh() {
		return this.recShortNameTh;
	}

	public void setRecShortNameTh(String recShortNameTh) {
		this.recShortNameTh = recShortNameTh;
	}
	
	@Column(name = "REC_SHORT_NAME_EN", nullable = false, length = 100)
	public String getRecShortNameEn() {
		return this.recShortNameEn;
	}

	public void setRecShortNameEn(String recShortNameEn) {
		this.recShortNameEn = recShortNameEn;
	}

	@Column(name = "REC_NAME_TH", nullable = false, length = 800)
	public String getRecNameTh() {
		return this.recNameTh;
	}

	public void setRecNameTh(String recNameTh) {
		this.recNameTh = recNameTh;
	}

	@Column(name = "REC_NAME_EN", nullable = false, length = 800)
	public String getRecNameEn() {
		return this.recNameEn;
	}

	public void setRecNameEn(String recNameEn) {
		this.recNameEn = recNameEn;
	}

	@Column(name = "CREATE_BY", nullable = false, length = 20)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", nullable = false, length = 26)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "UPDATE_BY", nullable = false, length = 20)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DATE", nullable = false, length = 26)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "REC_FILE_NO")
	public Integer getRecFileNo() {
		return this.recFileNo;
	}

	public void setRecFileNo(Integer recFileNo) {
		this.recFileNo = recFileNo;
	}

	@Column(name = "IMAGE_PATH")
	public Blob getImagePath() {
		return this.imagePath;
	}

	public void setImagePath(Blob imagePath) {
		this.imagePath = imagePath;
	}

	@JsonManagedReference
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "masterReceiverUnit")
	public List<EpayReceiverPaymentLine> getEpayReceiverPaymentLines() {
		return this.epayReceiverPaymentLines;
	}

	public void setEpayReceiverPaymentLines(List<EpayReceiverPaymentLine> epayReceiverPaymentLines) {
		this.epayReceiverPaymentLines = epayReceiverPaymentLines;
	}

}
