package th.go.rd.rdepaymentservice.entity;
// Generated Jul 17, 2018 10:14:52 AM by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * MasterReceiverType generated by hbm2java
 */
@Entity
@Table(name = "MASTER_RECEIVER_TYPE")
public class MasterReceiverType implements java.io.Serializable {

	private int receiverType;
	private String descriptionTh;
	private String descriptionEn;
	private List<MasterReceiverUnit> masterReceiverUnits = new ArrayList<>();

	public MasterReceiverType() {
	}

	public MasterReceiverType(int receiverType) {
		this.receiverType = receiverType;
	}
	public MasterReceiverType(int receiverType, String descriptionTh, String descriptionEn, List<MasterReceiverUnit> masterReceiverUnits) {
		this.receiverType = receiverType;
		this.descriptionTh = descriptionTh;
		this.descriptionEn = descriptionEn;
		this.masterReceiverUnits = masterReceiverUnits;
	}

	@Id

	@Column(name = "RECEIVER_TYPE", unique = true, nullable = false)
	public int getReceiverType() {
		return this.receiverType;
	}

	public void setReceiverType(int receiverType) {
		this.receiverType = receiverType;
	}

	@Column(name = "DESCRIPTION_TH", length = 200)
	public String getDescriptionTh() {
		return this.descriptionTh;
	}

	public void setDescriptionTh(String descriptionTh) {
		this.descriptionTh = descriptionTh;
	}

	@Column(name = "DESCRIPTION_EN", length = 200)
	public String getDescriptionEn() {
		return this.descriptionEn;
	}

	public void setDescriptionEn(String descriptionEn) {
		this.descriptionEn = descriptionEn;
	}

	@JsonManagedReference
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "masterReceiverType",cascade=CascadeType.ALL)
	public List<MasterReceiverUnit> getMasterReceiverUnits() {
		return this.masterReceiverUnits;
	}

	public void setMasterReceiverUnits(List<MasterReceiverUnit> masterReceiverUnits) {
		this.masterReceiverUnits = masterReceiverUnits;
	}

}
