package th.go.rd.rdepaymentservice.entity;
// Generated Jul 17, 2018 10:14:52 AM by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * MasterPaymentStatus generated by hbm2java
 */
@Entity
@Table(name = "MASTER_PAYMENT_STATUS")
public class MasterPaymentStatus implements java.io.Serializable {

	private int masterPaymentStatusId;
	private String descriptionTh;
	private String descriptionEn;
	private List<EpayTaxPaymentInbound> epayTaxPaymentInbounds = new ArrayList<>();

	public MasterPaymentStatus() {
	}

	public MasterPaymentStatus(int masterPaymentStatusId) {
		this.masterPaymentStatusId = masterPaymentStatusId;
	}
	public MasterPaymentStatus(int masterPaymentStatusId, String descriptionTh, String descriptionEn, List<EpayTaxPaymentInbound> epayTaxPaymentInbounds) {
		this.masterPaymentStatusId = masterPaymentStatusId;
		this.descriptionTh = descriptionTh;
		this.descriptionEn = descriptionEn;
		this.epayTaxPaymentInbounds = epayTaxPaymentInbounds;
	}

	@Id

	@Column(name = "MASTER_PAYMENT_STATUS_ID", unique = true, nullable = false)
	public int getMasterPaymentStatusId() {
		return this.masterPaymentStatusId;
	}

	public void setMasterPaymentStatusId(int masterPaymentStatusId) {
		this.masterPaymentStatusId = masterPaymentStatusId;
	}

	@Column(name = "DESCRIPTION_TH", length = 200)
	public String getDescriptionTh() {
		return this.descriptionTh;
	}

	public void setDescriptionTh(String descriptionTh) {
		this.descriptionTh = descriptionTh;
	}

	@Column(name = "DESCRIPTION_EN", length = 200)
	public String getDescriptionEn() {
		return this.descriptionEn;
	}

	public void setDescriptionEn(String descriptionEn) {
		this.descriptionEn = descriptionEn;
	}

	@JsonManagedReference
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "masterPaymentStatus",cascade=CascadeType.ALL)
	public List<EpayTaxPaymentInbound> getEpayTaxPaymentInbounds() {
		return this.epayTaxPaymentInbounds;
	}

	public void setEpayTaxPaymentInbounds(List<EpayTaxPaymentInbound> epayTaxPaymentInbounds) {
		this.epayTaxPaymentInbounds = epayTaxPaymentInbounds;
	}

}
