package th.go.rd.rdepaymentservice.entity;
// Generated Sep 17, 2018 10:48:55 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PaymentLog generated by hbm2java
 */
@Entity
@Table(name = "PAYMENT_LOG")
public class PaymentLog implements java.io.Serializable {

	private long paymentLogId;
	private String apiCode;
	private Date requestTime;
	private Date responseTime;
	private String httpResponseCode;
	private String responseCode;
	private String responseMessage;
	private String ip;
	private String userName;
	private String description;

	public PaymentLog() {
	}

	public PaymentLog(long paymentLogId, String apiCode, Date requestTime, Date responseTime, String httpResponseCode, String responseCode, String userName) {
		this.paymentLogId = paymentLogId;
		this.apiCode = apiCode;
		this.requestTime = requestTime;
		this.responseTime = responseTime;
		this.httpResponseCode = httpResponseCode;
		this.responseCode = responseCode;
		this.userName = userName;
	}
	public PaymentLog(long paymentLogId, String apiCode, Date requestTime, Date responseTime, String httpResponseCode, String responseCode, String responseMessage, String ip, String userName,
			String description) {
		this.paymentLogId = paymentLogId;
		this.apiCode = apiCode;
		this.requestTime = requestTime;
		this.responseTime = responseTime;
		this.httpResponseCode = httpResponseCode;
		this.responseCode = responseCode;
		this.responseMessage = responseMessage;
		this.ip = ip;
		this.userName = userName;
		this.description = description;
	}

	@Id
	@SequenceGenerator(name="PAYMENT_LOG_ID_SEQ", sequenceName="PAYMENT_LOG_ID_SEQ", allocationSize=1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="PAYMENT_LOG_ID_SEQ")
	@Column(name = "PAYMENT_LOG_ID", unique = true, nullable = false)
	public long getPaymentLogId() {
		return this.paymentLogId;
	}

	public void setPaymentLogId(long paymentLogId) {
		this.paymentLogId = paymentLogId;
	}

	@Column(name = "API_CODE", nullable = false, length = 20)
	public String getApiCode() {
		return this.apiCode;
	}

	public void setApiCode(String apiCode) {
		this.apiCode = apiCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REQUEST_TIME", nullable = false, length = 26)
	public Date getRequestTime() {
		return this.requestTime;
	}

	public void setRequestTime(Date requestTime) {
		this.requestTime = requestTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RESPONSE_TIME", nullable = false, length = 26)
	public Date getResponseTime() {
		return this.responseTime;
	}

	public void setResponseTime(Date responseTime) {
		this.responseTime = responseTime;
	}

	@Column(name = "HTTP_RESPONSE_CODE", nullable = false, length = 20)
	public String getHttpResponseCode() {
		return this.httpResponseCode;
	}

	public void setHttpResponseCode(String httpResponseCode) {
		this.httpResponseCode = httpResponseCode;
	}

	@Column(name = "RESPONSE_CODE", nullable = false, length = 20)
	public String getResponseCode() {
		return this.responseCode;
	}

	public void setResponseCode(String responseCode) {
		this.responseCode = responseCode;
	}

	@Column(name = "RESPONSE_MESSAGE", length = 1000)
	public String getResponseMessage() {
		return this.responseMessage;
	}

	public void setResponseMessage(String responseMessage) {
		this.responseMessage = responseMessage;
	}

	@Column(name = "IP", length = 20)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "USER_NAME", nullable = false, length = 100)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "DESCRIPTION", length = 2000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
